Number of stores not made persistent: 1
Stores not made persistent properly:
[0]    at 0x........: main (redundant_logging3.c:25)
	Address: 0x........	size: 4	state: DIRTY
Total memory not made persistent: 4

Number of overlapping regions registered in a same transactions: 1
Overlapping regions:
[0]    at 0x........: main (redundant_logging3.c:24)
	Address: 0x........	size: 4	tx_id: ...
   First registered here:
[0]'   at 0x........: main (redundant_logging3.c:22)
	Address: 0x........	size: 4	tx_id: ...
ERROR SUMMARY: 2 errors
