Number of stores not made persistent: 4
Stores not made persistent properly:
[0]    at 0x........: main (redundant_logging5.c:26)
	Address: 0x........	size: 1	state: DIRTY
[1]    at 0x........: main (redundant_logging5.c:27)
	Address: 0x........	size: 2	state: DIRTY
[2]    at 0x........: main (redundant_logging5.c:28)
	Address: 0x........	size: 4	state: DIRTY
[3]    at 0x........: main (redundant_logging5.c:29)
	Address: 0x........	size: 8	state: DIRTY
Total memory not made persistent: 15

Number of stores made without adding to transaction: 2
Stores made without adding to transactions:
[0]    at 0x........: main (redundant_logging5.c:26)
	Address: 0x........	size: 1
[1]    at 0x........: main (redundant_logging5.c:29)
	Address: 0x........	size: 8

Number of overlapping regions registered in a same transactions: 1
Overlapping regions:
[0]    at 0x........: main (redundant_logging5.c:23)
	Address: 0x........	size: 2	tx_id: ...
   First registered here:
[0]'   at 0x........: main (redundant_logging5.c:22)
	Address: 0x........	size: 2	tx_id: ...

Number of active transactions: 1
[0]    at 0x........: main (redundant_logging5.c:18)
	tx_id: ...	 nesting: 1
ERROR SUMMARY: 8 errors

Number of stores not made persistent: 4
Stores not made persistent properly:
[0]    at 0x........: main (redundant_logging5.c:26)
	Address: 0x........	size: 1	state: DIRTY
[1]    at 0x........: main (redundant_logging5.c:35)
	Address: 0x........	size: 2	state: DIRTY
[2]    at 0x........: main (redundant_logging5.c:28)
	Address: 0x........	size: 4	state: DIRTY
[3]    at 0x........: main (redundant_logging5.c:39)
	Address: 0x........	size: 8	state: DIRTY
Total memory not made persistent: 15

Number of stores made without adding to transaction: 3
Stores made without adding to transactions:
[0]    at 0x........: main (redundant_logging5.c:26)
	Address: 0x........	size: 1
[1]    at 0x........: main (redundant_logging5.c:29)
	Address: 0x........	size: 8
[2]    at 0x........: main (redundant_logging5.c:35)
	Address: 0x........	size: 2

Number of overlapping regions registered in a same transactions: 1
Overlapping regions:
[0]    at 0x........: main (redundant_logging5.c:23)
	Address: 0x........	size: 2	tx_id: ...
   First registered here:
[0]'   at 0x........: main (redundant_logging5.c:22)
	Address: 0x........	size: 2	tx_id: ...
ERROR SUMMARY: 8 errors
